title: Light Exchange
description: A site documenting the Light Exchange community in VRChat
theme: just-the-docs
color_scheme: dark
search_enabled: false

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
